---

- name: template elasticsearch.yml
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: root
    mode: 0644
  notify: es restart

- name: template logging.yml
  template:
    src: "logging-{{es_version}}.yml.j2"
    dest: "/etc/elasticsearch/logging.yml"
    owner: root
    group: root
    mode: 0644
  notify: es restart

- name: template sysconfig cfg
  template:
    src=elasticsearch-{{es_version}}.sysconfig.j2
    dest=/etc/sysconfig/elasticsearch
    owner=root
    group=root
    mode=0644
  notify: es restart

- name: service enable, start
  service: name=elasticsearch state={{es_svc_state}} enabled={{es_svc_enabled}}

# Install Other Generic Plugins
- include: plugins.yml
  when: (es_plugins is defined)

