---
# from https://raw.githubusercontent.com/Traackr/ansible-elasticsearch/master/tasks/plugins.yml
#
# Install Elasticsearch Plugins
#
# You will need to define an array called 'es_plugins' in your playbook or inventory, such that:
#
# es_plugins:
#  - { name: '<plugin name>', url: '<[optional] plugin url>' }
#  - ...
# where if you were to install the plugin via bin/plugin, you would type:
#
# bin/plugin -install <plugin name>
#
# or
#
# bin/plugin -install <plugin name> -url <plugin url>

# Example for https://github.com/elasticsearch/elasticsearch-mapper-attachments (bin/plugin -install elasticsearch/elasticsearch-mapper-attachments/1.9.0):
# es_plugins:
#  - { name: 'elasticsearch/elasticsearch-mapper-attachments/1.9.0' }
#
# Example for https://github.com/richardwilly98/elasticsearch-river-mongodb (bin/plugin -i com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/1.7.1):
# es_plugins:
#  - { name: 'com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/1.7.1' }
#
# Example for https://github.com/imotov/elasticsearch-facet-script (bin/plugin -install facet-script -url http://dl.bintray.com/content/imotov/elasticsearch-plugins/elasticsearch-facet-script-1.1.2.zip):
# es_plugins:
#  - { name: 'facet-script', url: 'http://dl.bintray.com/content/imotov/elasticsearch-plugins/elasticsearch-facet-script-1.1.2.zip' }

# Loop though es_plugins and install them
#- name: remove plugins if they exist
#  action: >
#    shell bin/plugin --remove {{ item.name }}
#    chdir={{ es_home_dir }}
#  with_items: es_plugins
#  ignore_errors: yes
- name: install plugins by Name
  shell: bin/plugin -install {{ item.name }}
  args:
    chdir: "{{ es_home_dir }}"
    creates: "{{es_plugins_dir}}/{{item.dir}}"
  when: item.url is not defined and item.dir is defined
  with_items: es_plugins
  ignore_errors: yes
- name: install plugins by URL
  shell: bin/plugin -install {{ item.name }} -url {{ item.url }}
  args:
    chdir: "{{ es_home_dir }}"
    creates: "{{es_plugins_dir}}/{{item.dir}}"
  when: item.url is defined and item.dir is defined
  with_items: es_plugins
  ignore_errors: yes
# Fix permissions
- name: fix plugin dir permissions
  file: >
    path="{{ es_plugins_dir }}" state=directory
    owner={{ es_user }} group={{ es_group }}
    recurse=yes
