---
# from https://raw.githubusercontent.com/Traackr/ansible-elasticsearch/master/tasks/plugins.yml

# Loop though es_plugins and install them
#- name: remove plugins if they exist
#  action: >
#    shell bin/plugin --remove {{ item.name }}
#    chdir={{ es_home_dir }}
#  with_items: "{{es_plugins}}"
#  ignore_errors: yes

- set_fact:
    es_plugin_p_install: "-install"
    es_plugin_p_url: "-url"
  when: es_version == "1.4"

- set_fact:
    es_plugin_p_install: install
    es_plugin_p_url: "url"
  when: es_version == "2.x"

- name: install plugins by Name
  shell: bin/plugin {{es_plugin_p_install}} {{ item.name }}
  args:
    chdir: "{{ es_home_dir }}"
    creates: "{{es_plugins_dir}}/{{item.dir}}"
  when: item.url is not defined and item.dir is defined and es_version in item.versions
  with_items: "{{es_plugins}}"
  ignore_errors: yes

- name: install plugins by URL
  shell: bin/plugin {{es_plugin_p_install}} {{ item.name }} {{es_plugin_p_url}} {{ item.url }}
  args:
    chdir: "{{ es_home_dir }}"
    creates: "{{es_plugins_dir}}/{{item.dir}}"
  when: item.url is defined and item.dir is defined
  with_items: "{{es_plugins}}"
  ignore_errors: yes

# Fix permissions
- name: fix plugin dir permissions
  file: >
    path="{{ es_plugins_dir }}" state=directory
    owner={{ es_user }} group={{ es_group }}
    recurse=yes
